### ISSUE TITLE
Number

### ISSUE THREAD

**Issue by akleiber** [aichbauer/node-convert-string-to-number#2]
Why can't you use `Number(...)`?

```
> Number(2.2)
2.2
> Number(2)
2
> Number('2')
2
> Number(0)
0
>
> Number(true)
1
> Number(false)
0
> Number('this is batman')
NaN
```

**Comment by aichbauer** [comment]
There is only one reason why (i do not know if there are other use cases... but that is why I created it):

you do not want to mutate values for for your csv files... e.g. you need the csv to contain decimals (e.g. you want the value to be a float)

if you use `Number("2.0")` you will get 2 and if you want your csv to be consistent e.g always a float, always a integer etc... you need to ensure that a string like "2.0" is encoded as 2.0 and not as 2... or otherwise you will encounter problems when using it... specially if you use it in a typesafe language...

Does this answer your question?

![Screenshot_20191107-124158__01](https://user-images.githubusercontent.com/14862422/68390208-b3992a80-015c-11ea-8691-cc4e2b1d543b.jpg)
